petcare:
  jwt:
    secret: verySecretChangeThisInProd_!change_me!
    expiration-ms: 3600000   # 1 hour
spring:
  datasource:
    url: jdbc:h2:mem:petcare;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
      path: /h2-console
